// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKsyYJaRynOBL_gp1ybXmTgsrXKX8zmDg',
    appId: '1:654407135297:web:892e5997a21633c6c196c0',
    messagingSenderId: '654407135297',
    projectId: 'document-tracking-de959',
    authDomain: 'document-tracking-de959.firebaseapp.com',
    storageBucket: 'document-tracking-de959.firebasestorage.app',
    measurementId: 'G-LVTXZWFX4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbFuFaGR_m4f6tklYAhTKW92pyPcZpMOI',
    appId: '1:654407135297:android:6c964c742886e1e7c196c0',
    messagingSenderId: '654407135297',
    projectId: 'document-tracking-de959',
    storageBucket: 'document-tracking-de959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV4AiFBjGAw26wfdQ3HB1_Qpi3-bkOgac',
    appId: '1:654407135297:ios:217f9bba44130f58c196c0',
    messagingSenderId: '654407135297',
    projectId: 'document-tracking-de959',
    storageBucket: 'document-tracking-de959.firebasestorage.app',
    iosBundleId: 'com.example.documentTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV4AiFBjGAw26wfdQ3HB1_Qpi3-bkOgac',
    appId: '1:654407135297:ios:217f9bba44130f58c196c0',
    messagingSenderId: '654407135297',
    projectId: 'document-tracking-de959',
    storageBucket: 'document-tracking-de959.firebasestorage.app',
    iosBundleId: 'com.example.documentTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKsyYJaRynOBL_gp1ybXmTgsrXKX8zmDg',
    appId: '1:654407135297:web:69ea209a0e9148d1c196c0',
    messagingSenderId: '654407135297',
    projectId: 'document-tracking-de959',
    authDomain: 'document-tracking-de959.firebaseapp.com',
    storageBucket: 'document-tracking-de959.firebasestorage.app',
    measurementId: 'G-SFHJ0P0F6Q',
  );
}
